repos:
-   repo: local
    hooks:
    -   id: test
        name: test
        entry: pytest -v -s test
        stages:
            - "push"
            - "commit"
        language: system
        pass_filenames: false
        always_run: true
        types: [python]
