version: "3"

services:
  app:
    container_name: app
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        # [Choice] Python version: 3, 3.8, 3.7, 3.6
        VARIANT: 3.8
        # [Choice] Node.js version: none, lts/*, 16, 14, 12, 10
        NODE_VERSION: "lts/*"
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    env_file: app.env
    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    container_name: postgres
    image: postgres:14.4-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: app.env
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  web:
    container_name: web
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./web/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/ssl:/etc/nginx/ssl

  schemaspy:
    image: schemaspy/schemaspy:snapshot
    container_name: "schemaspy"
    volumes:
      - ./schemaspy/output:/output
      - ./schemaspy/postgresql-42.4.0.jar:/postgresql-42.4.0.jar
      - ./schemaspy/make.sh:/make.sh
    tty: true
    entrypoint: /bin/sh
    env_file: app.env

  schemaspy_web:
    image: nginx:alpine
    container_name: "schemaspy_web"
    ports:
      - "8081:80"
    volumes:
      - ./schemaspy/output:/usr/share/nginx/html
volumes:
  postgres-data:
