name: Reuse Workflow

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: echo
        run: echo ${{ inputs.python-version }}
